apiVersion: v1
kind: Service
metadata:
  name: flagger-loadtester
  namespace: test
  labels:
    app: flagger-loadtester
spec:
  type: ClusterIP
  selector:
    app: flagger-loadtester
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080