kind: Service
apiVersion: v1
metadata:
  name: ingress
  namespace: test
spec:
  selector:
    app: ingress
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
