apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: ingress
  namespace: test
spec:
  meshName: global
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostName: ingress.test
  backends:
    - virtualService:
        virtualServiceName: podinfo.test
